"""
Digital Erythrocyte Layer — Anomaly Detection Module.
Fulfills erythrocyte_spec.md for detecting static and oscillating weight distortions.
"""

import math
from typing import List, Dict, Any
# Using absolute import matching the project root execution context
from core_engine import CriticalityMatrix, Weight

def calculate_provenance_ratio(weight: Weight) -> float:
    """
    Computes the fraction of recent changes generated by legitimate system logic
    (tagged as 'update_loop' or 'erythrocyte_correction').
    """
    if not weight.history:
        return 1.0
    
    legitimate_count = sum(
        1 for entry in weight.history 
        if entry.source in ("update_loop", "erythrocyte_correction")
    )
    return legitimate_count / len(weight.history)

def calculate_variance(values: List[float]) -> float:
    """Standard statistical variance lookup."""
    if len(values) < 2:
        return 0.0
    mean = sum(values) / len(values)
    return sum((x - mean) ** 2 for x in values) / (len(values) - 1)

def scan_matrix(matrix: CriticalityMatrix, min_samples: int = 5) -> List[Dict[str, Any]]:
    """
    Scans the entire CriticalityMatrix for signatures of external weight poisoning.
    Returns a list of detected anomalies matching Section 3 of the spec.
    """
    anomalies = []
    
    for name in matrix.names():
        weight = matrix.get_weight(name)
        
        # We need enough history to establish a baseline signature
        if len(weight.history) < min_samples:
            continue
            
        p_ratio = calculate_provenance_ratio(weight)
        history_values = [entry.new_value for entry in weight.history]
        
        offset = abs(weight.value - weight.baseline)
        variance = calculate_variance(history_values)
        
        is_poisoning_candidate = (offset > 0.0) and (p_ratio < 0.7)
        
        if is_poisoning_candidate:
            # Classification logic based on variance thresholds (spec Section 3)
            # High variance indicates unstable oscillation (dangerous class).
            # Threshold is per-weight (weight.variance_threshold), not a
            # single module-wide constant — a fast-adapting model parameter
            # and a near-constant W0 invariant have different natural
            # volatility and shouldn't share one hardcoded number.
            if variance > weight.variance_threshold:
                distortion_type = "oscillating"
            else:
                distortion_type = "static"
                
            anomalies.append({
                "weight": name,
                "distortion": distortion_type,
                "poisoning_candidate": True,
                "provenance_ratio": round(p_ratio, 3),
                "offset": round(offset, 4),
                "spread": round(math.sqrt(variance), 4),
                "variance_threshold_used": weight.variance_threshold,
            })
            
    return anomalies